version: '3'

services:
  api:
    build: .
    image: flask_restful
    container_name: ldap_api
    environment: 
            - LDAP_API_ENVIRONMENT=${LDAP_API_ENVIRONMENT}
            - FLASK_ENV=${LDAP_API_ENVIRONMENT}
    expose: 
      - 5000
    ports:
    - "${API_HOST_PORT}:5000"
    volumes:
    - .:/api
    restart: always
    working_dir: /api
    command: python run.py

networks: 
  default:
    external:
      name: tesis