sql_server:
  connection_string: 
    server:
      - 'DESKTOP-50O75DL\SQLEXPRESS'
  restore_query:
    bak_source:
      - 'D:\Others\Tesis\resources\Nomina.bak'
    data_destination:
      - 'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\PLANTILLA_RH.mdf'
    logs_destination:
      - 'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\PLANTILLA_RH.ldf'
workers_schema: # First item is the property name, sencond one is the index (0 based) in database row
  - ["area", 6]
  - ["cargo", 5]
  - ["ci", 0]
  - ["cn", 1]
  - ["sexo", 2]
  - ["sn", [3, 4]]


  # PAra todos

  # objectclass: posixAccount
  # objectclass: shadowAccount
  # uidnumber: ----
  # gidnumber: ----
  # homedirectory: ---- 