version: '3'

services:
  api:
    build: .
    image: flask_restful
    container_name: ldap_api
    expose: 
      - 5000
    ports:
    - "${API_HOST_PORT}:5000"
    volumes:
    - .:/api
    restart: always
    working_dir: /api
    command: python run.py